DROP TABLE IF EXISTS  CONFIG;
DROP TABLE IF EXISTS  JOB;
CREATE TABLE JOB (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, OBJECTS CAHR(100) NOT NULL, COUNT INTEGER NOT NULL, KAFKA_HOST CHAR(100), ZOOKEEPER_HOST CHAR(100), TOPICS CHAR(200), STATUS CHAR(25));
CREATE TABLE CONFIG (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , KEY CHAR(500) NOT NULL UNIQUE, VALUE CHAR(500));
INSERT INTO CONFIG (KEY,VALUE) VALUES ('vehicles_fields', 'accountTId,name,sn,mnf,mdl,objCat,crdtDt,updtDt,tId');
INSERT INTO JOB (OBJECTS, COUNT, KAFKA_HOST, ZOOKEEPER_HOST, TOPICS, STATUS) VALUES ('VEHICLES,SENSORS',10,'localhost:9200','localhost:2181','TOR_TMP','NEW');
