DROP TABLE IF EXISTS  CONFIG;
DROP TABLE IF EXISTS  JOB;
CREATE TABLE JOB (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, OBJECTS CAHR(100) NOT NULL, COUNT INTEGER NOT NULL, KAFKA_HOST CHAR(100), ZOOKEEPER_HOST CHAR(100), TOPICS CHAR(200), STATUS CHAR(25));
CREATE TABLE CONFIG (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , KEY CHAR(500) NOT NULL UNIQUE, VALUE CHAR(500));
